#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#
#leitor:
#  limite-emprestimos: 5
#  prazo-emprestimo: 7
